# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/ALU.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/Clock_Divider.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/Debouncer.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/Display_Controller.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/FA.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/HA.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/Reg.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/SHL.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/SHR.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/andd.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/multip.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/nott.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/orr.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/sub.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/submult.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/sum.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/xorr.vhd}
  {C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/sources_1/new/Basys3.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Manuel Aguirre/Desktop/intento de mult/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}]


synth_design -top Basys3 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Basys3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb"
